### ISSUE TITLE
ReadMe Template

### ISSUE THREAD

**Issue by CraigBuckmaster** [paladinarcher/accelerators#10]
**Description**
As P&A Staff
I want a readme template
so that I can easily and quickly setup a readme for a new project

A templated ReadMe that is easy to read/follow/and execute.

**Acceptance Criteria**
- [ ] Easy to read

- [ ] Instructions are easy to follow

- [ ] Follows Plain Language guidelines

**Comment by thegoodman99** [comment]
NOTES

1. Start with the most general information at the top (Name, Description, Examples) and if the reader maintains interest, narrow down to specifics (API, Installation). This makes it easy for readers to "short circuit" and continue the hunt for the right module elsewhere without wasting time delving into unnecessary details.
