### ISSUE TITLE
Capabilities Statement lightning demos + expert interview

### ISSUE THREAD

**Issue by CraigBuckmaster** [paladinarcher/accelerators#110]
**Description:** _type of prototype: paper, wireframe, digital design, or code?_

**Link to Design Prototype:** 

**Acceptance Criteria:**
- [ ] Incorporates design thinking processes: Discover, Define, Develop, Deliver
- [ ] Each process involves techniques of divergent and convergent thinking
- [ ] Utilizes user personas
- [ ] Incorporates empathy mapping
- [ ] Incorporates journey mapping
- [ ] Design solution is desirable by users/customers
- [ ] Solution is feasible (can be achieved with what we have or can acquire)
- [ ] Solution is viable (value produced is enough to justify cost)
- [ ] Solution is sustainable (it is proactively managed to account for its expected product-market lifecycle)

**Comment by moroni-pickering** [comment]
Craig - Rules/Guidelines for Capabilities Statements (3m)
Liz - Examples from online : design focused (3m)
Craig -  InnoVet's (3m), LinkedIn Guy/Privateer Company (3m)
Moroni - Our statement (3m), How to videos with remaining time
Paul - Extra Focused on Capturing Notes
