### ISSUE TITLE
VA IT Leader Persona

### ISSUE THREAD

**Issue by CraigBuckmaster** [paladinarcher/accelerators#111]
**Enabler Description:** 
Create a new technical manager persona based on Gov IT managers. 
https://paladinarcher.sharepoint.com/:w:/g/EWYhDRaZK7lDqB1fWRLegZYBXsOuNOtxRzDSmolZS8x-oA?e=NWFwjb

**Acceptance Criteria:**
- [x] Interview Moroni for affinity notes
- [x] Organize findings and notes
- [x] Duplicate the tech manager document and incorporate any new format data points.

**Comment by debsmith-ux** [comment]
Interview Notes with Moroni 
https://paladinarcher.sharepoint.com/:w:/r/_layouts/15/Doc.aspx?sourcedoc=%7Bd97b236d-343e-43e1-a8a9-ed1b2ca33623%7D&action=edit&wdPreviousSession=9afe0920-6995-4cc6-9923-bb036eed6e95

**Comment by debsmith-ux** [comment]
https://paladinarcher.sharepoint.com/:w:/g/EWYhDRaZK7lDqB1fWRLegZYBXsOuNOtxRzDSmolZS8x-oA?e=NWFwjb
