### ISSUE TITLE
Automate continuous testing repo

### ISSUE THREAD

**Issue by CraigBuckmaster** [paladinarcher/accelerators#114]
**Description:** 
Exactly as Keola said, automate the continuous testing repo. 

As a, developer
I want a continuous testing framework that is automated to use 
So that I can quickly edit and automate my testing

**Acceptance Criteria:** 
- [x] Given the template repo is being used, when new code is pushed into it, then the continuous testing framework runs the tests. 
- [x] Given the template repo is being used, when tests are run, then results are visible 

[User Story Template & Checklist](https://paladinarcher.sharepoint.com/:w:/g/EcZeUGukawJKqcYMs5evUksB-N6pj3Gy6pl7e14uNBz_zg?e=Uc7nAX)

**Comment by thegoodman99** [comment]
<img width="933" alt="Screen Shot 2021-01-15 at 10 16 27 AM" src="https://user-images.githubusercontent.com/40801662/104758681-0042a300-571c-11eb-9a0d-6eca00b8f67c.png">
<img width="1411" alt="Screen Shot 2021-01-15 at 10 20 35 AM" src="https://user-images.githubusercontent.com/40801662/104758683-00db3980-571c-11eb-906a-3426e9da8640.png">

These two images above show tests being done automatically with the results.

<img width="1432" alt="Screen Shot 2021-01-15 at 10 20 55 AM" src="https://user-images.githubusercontent.com/40801662/104758798-2c5e2400-571c-11eb-8232-b9794e18ad2f.png">
<img width="300" alt="Screen Shot 2021-01-15 at 10 21 28 AM" src="https://user-images.githubusercontent.com/40801662/104758810-2ec07e00-571c-11eb-9d9f-7733e6c76c2e.png">

These next two images are of the completed passed and failed test as well as an image of the code that controls the frequency of tests.
