### ISSUE TITLE
Journey Map for Enhance P&A Website 

### ISSUE THREAD

**Issue by probbins79** [paladinarcher/accelerators#119]
**Enabler Description:** 
Enhance P&A Website Journey Map

**Acceptance Criteria:**
- [x] Analyze current website with heuristic markup
- [x] Company wide user test worksheet: Liz write up homework action sheet 

Enabler Description tells what you will do. E.g. Record or buy some realistic sounds so we can test them with actual users. 
Acceptance Criteria consists of a concise statement for each part of the story detailing an action that must be taken. E.g. Acquire sound samples.

**Comment by eapowell** [comment]
P&A Company Simple User Test Scenarios
https://paladinarcher-my.sharepoint.com/:w:/p/elizabeth/EQIUFlYf2EROsd6Br10RgcwBga6wCYJXddTiRY6wC5BiEA?e=eBg90V

**Comment by eapowell** [comment]
Heuristic Evaluation
https://paladinarcher-my.sharepoint.com/:p:/p/elizabeth/EQWC-xKQvF5OvMjwjXmxULMBv9G5FoNVX45Zg_X6eIrbKw?e=PX3X7X
