### ISSUE TITLE
Refine VA IT Leader Persona 

### ISSUE THREAD

**Issue by CraigBuckmaster** [paladinarcher/accelerators#133]
**Enabler Description:** 

**Acceptance Criteria:**
- [x] Update the ORG chart
- [x] Remove the notes on the persona and put them in their sections 
- [x] Update the needs
- [x] Update Influencer section
- [x] Update Challenges
- [ ] 

Enabler Description tells what you will do. E.g. Record or buy some realistic sounds so we can test them with actual users. 
Acceptance Criteria consists of a concise statement for each part of the story detailing an action that must be taken. E.g. Acquire sound samples.

**Comment by eapowell** [comment]
https://paladinarcher.sharepoint.com/:w:/r/_layouts/15/doc2.aspx?sourcedoc=%7BF531216B-8436-4700-A539-7EB72FA1C654%7D&file=VA%20IT%20Leader%20Role.docx&action=default&mobileredirect=true&DefaultItemOpen=1&ct=1611756496249&wdOrigin=OFFICECOM-WEB.MAIN.OTHER&cid=854942eb-4ca5-4e35-a7f8-412e24cc85a1
