### ISSUE TITLE
Define CT within PDMP 

### ISSUE THREAD

**Issue by CraigBuckmaster** [paladinarcher/accelerators#135]
**Enabler Description:** 
Use the CT Template YOU created 

**Acceptance Criteria:**
- [ ] Create all the stories needed to use CT on PDMP
- [ ] Define top level epic for CT on PDMP

Enabler Description tells what you will do. E.g. Record or buy some realistic sounds so we can test them with actual users. 
Acceptance Criteria consists of a concise statement for each part of the story detailing an action that must be taken. E.g. Acquire sound samples.

**Comment by thegoodman99** [comment]
https://github.com/paladinarcher/accelerators/issues#workspaces/pa-accelerators-5fa407a26c2540001731f9cf/board?epics=310316786_136&filterLogic=any&useDefaultFilterLogic=false&repos=310316786
