### ISSUE TITLE
P&A Website Enhancements

### ISSUE THREAD

**Issue by CraigBuckmaster** [paladinarcher/accelerators#143]
**Enabler Description:** 
We don't want the website to be VA focused. 

**Acceptance Criteria:**
- [x] Change mission statement and put it in the About us page- 
- [x] Add a small business past performance (eHX spot)
- [x] Add something non-VA to "Why P&A" section
- [x] Update key benefits to current strategy
- [x] Update Services Page - Remove assessments/focus on DevSecOps
- [x] Add Craig to Officers on About us Page
- [x] Any simple aesthetic changes from Liz
- [x] Change Success Stories link to 'Case Studies' 
- [ ] Replace Continuous Quality title on carousel with something more relevant.

Enabler Description tells what you will do. E.g. Record or buy some realistic sounds so we can test them with actual users. 
Acceptance Criteria consists of a concise statement for each part of the story detailing an action that must be taken. E.g. Acquire sound samples.

**Comment by eapowell** [comment]
I added a new services page as a draft. As soon as that is fine tuned...it can be published and take the place of the old
