### ISSUE TITLE
Prototype SCCTool

### ISSUE THREAD

**Issue by CraigBuckmaster** [paladinarcher/accelerators#147]
**Description:** 

As a P&A Technologist
I want a tool that will gauge my customer centricity capabilities
So that I can understand where I'm at in focus areas. 

**Acceptance Criteria:** 
- [ ] Given I have the SCCTool, when learning how to use the tool, then I can easily follow the instructions
- [ ] Given I have read the instructions and understand them, when evaluating my CCC, then I can self rate using a spreadsheet
- [ ] Given that I have completed self-evaluation, when I click on the results tab, then I can see my results in a Growth Orb. 
- [x] Use the LASSIE Solution sketch combined with the growth pro sketch.

[User Story Template & Checklist](https://paladinarcher.sharepoint.com/:w:/g/EcZeUGukawJKqcYMs5evUksB-N6pj3Gy6pl7e14uNBz_zg?e=Uc7nAX)

**Comment by eapowell** [comment]
https://paladinarcher.sharepoint.com/:x:/g/EUGai9wk95tAoLERsEYibEcBx6MyTLMScwnmvdjlobrF7A?e=g9Xslq
