### ISSUE TITLE
SCCTool Recommendations 

### ISSUE THREAD

**Issue by CraigBuckmaster** [paladinarcher/accelerators#148]
**Enabler Description:** 
Compile resources (SAFe stuff, extreme service handbook, etc) for the SCCTool to reference. 

**Acceptance Criteria:**
- [x] Link (hover text, etc) to elaborate on questions that may not be super clear
- [x] Results has additional resources for each section and question

Enabler Description tells what you will do. E.g. Record or buy some realistic sounds so we can test them with actual users. 
Acceptance Criteria consists of a concise statement for each part of the story detailing an action that must be taken. E.g. Acquire sound samples.

**Comment by eapowell** [comment]
Where will this live? Word doc? Web page?

**Comment by eapowell** [comment]
Link to tool prototype
https://paladinarcher.sharepoint.com/:x:/g/EUGai9wk95tAoLERsEYibEcBx6MyTLMScwnmvdjlobrF7A?e=g9Xslq
