### ISSUE TITLE
Template Repo

### ISSUE THREAD

**Issue by CraigBuckmaster** [paladinarcher/accelerators#15]
**Description**
As a product owner
I want a template repo of all of my accelerators
so that I can quickly start up a new project with my accelerators

A template repo to copy from for use on future projects

**Acceptance Criteria**
- [ ] Put Templates into a template repo

- [ ] Template repo holds all possible other templates

- [ ] Template repo is easily replicable for future use

**Comment by thegoodman99** [comment]
https://github.com/paladinarcher/Template-Repo
