### ISSUE TITLE
Walkthrough Document for SCCT

### ISSUE THREAD

**Issue by probbins79** [paladinarcher/accelerators#154]
**Enabler Description:** 
Create Mini- Handbook for the SCCT, describing what it is and how it works.

**Acceptance Criteria:**
- [x] Use the Outline created in Accelerator 15
- [x] Sharepoint in word
- [x] Describes how to use the tool in depth, including links for understanding.

Enabler Description tells what you will do. E.g. Record or buy some realistic sounds so we can test them with actual users. 
Acceptance Criteria consists of a concise statement for each part of the story detailing an action that must be taken. E.g. Acquire sound samples.

**Comment by eapowell** [comment]
Outline is in sharepoint titled guidebook outline

**Comment by debsmith-ux** [comment]
https://paladinarcher.sharepoint.com/:w:/r/_layouts/15/Doc.aspx?sourcedoc=%7BBA07362B-A866-4B23-AE9D-8291E7A77F11%7D&file=Outline%20for%20Guidebook%20for%20SCCTool.docx&action=default&mobileredirect=true

**Comment by debsmith-ux** [comment]
Walkthrough document: https://paladinarcher.sharepoint.com/:w:/r/_layouts/15/Doc.aspx?sourcedoc=%7BEF18C485-8D39-4900-A180-909579EC3910%7D&file=Walkthrough%20Document%20for%20SCCTool.docx&action=default&mobileredirect=true
