### ISSUE TITLE
SCCT Training Guidebook Outline

### ISSUE THREAD

**Issue by probbins79** [paladinarcher/accelerators#156]
**Enabler Description:** 
Figure out an Outline on how to train staff on qualities from SCCT

**Acceptance Criteria:**
- [x] Include Sharepoint or somewhere easily accessible 
- [x] Include Hits on major SCCT concepts
- [x] Include Links to helpful articles
- [x] Include Recommendations for further training/certifications 
- [x] Collaborate with 2+ team members

Enabler Description tells what you will do. E.g. Record or buy some realistic sounds so we can test them with actual users. 
Acceptance Criteria consists of a concise statement for each part of the story detailing an action that must be taken. E.g. Acquire sound samples.

**Comment by debsmith-ux** [comment]
Link to Outline in Sharepoint:https://paladinarcher.sharepoint.com/:w:/r/_layouts/15/Doc.aspx?sourcedoc=%7Bba07362b-a866-4b23-ae9d-8291e7a77f11%7D&action=editnew&Source=https%3A%2F%2Fpaladinarcher.sharepoint.com%2FSitePages%2FHome.aspx%3FRootFolder%3D%252FShared%2520Documents%252FAccelerators%26FolderCTID%3D0x0120007B2783255181B047A73D62C136503F91%26View%3D%257BF86FE795%252D1D48%252D4C5D%252DA3CC%252DBFAAEF12A977%257D
