### ISSUE TITLE
Questions List for Clients

### ISSUE THREAD

**Issue by probbins79** [paladinarcher/accelerators#157]
**Enabler Description:** 
List of Questions that can be used to discover what clients want and how to help them.

**Acceptance Criteria:**
- [ ] Questions will be designed to derive information relevant to clients' needs
- [x] Questions will be on sharepoint doc w link
https://paladinarcher.sharepoint.com/:x:/r/_layouts/15/Doc.aspx?sourcedoc=%7B20cab907-434f-4440-9830-7371b45a7cc6%7D&action=editnew&Source=https%3A%2F%2Fpaladinarcher.sharepoint.com%2FSitePages%2FHome.aspx&cid=74461539-ad08-4d94-acc3-53ada1d50f23

**Comment by eapowell** [comment]
Interview Jay, Wayne & DavidL for possible accelerator tool ideas
