### ISSUE TITLE
Usability Testing Template

### ISSUE THREAD

**Issue by CraigBuckmaster** [paladinarcher/accelerators#16]
**Description**
As a UX researcher (or anyone doing UX research)
I want a template to assist with best practices in usability testing for user feedback
So that I can be more efficient and avoid missing things I should remember

**Acceptance Criteria**
- [x] Follows best practices

- [x] RITE Usability Testing

- [x] Include Capturing The Findings

**Comment by debsmith-ux** [comment]
https://www.gartner.com/document/code/351011

**Comment by debsmith-ux** [comment]
https://digitalist.global/talks/continuous-ux-research/

**Comment by debsmith-ux** [comment]
Ensure that quality is a team focus by making use of communities of practice or guilds to discover, share and evolve best practices, shifting the focus of QA from quality assurance to quality assistance.
Drive a continuous approach to quality focused on prevention and automation, utilizing key agile practices such as BDD, pairing, static analysis and test automation that support continuous quality and the test pyramid.
Utilize “shift left” activities to drive faster feedback loops about software design and requirements, and “shift right” activities to measure the effectiveness of new software in achieving business goals.

**Comment by debsmith-ux** [comment]
![](https://www.gartner.com/resources/351000/351011/351011_0002.png)

**Comment by debsmith-ux** [comment]
the books Agile Testing and More Agile Testing by Lisa Crispin and Janet Gregory

**Comment by debsmith-ux** [comment]
Adopt the use of CoPs or guilds to discover and share best practices.
Shift the view of “quality is the job of…” from a role to the team.
Move from quality assurance to quality assistance (see the Case Study to see how Microsoft did this).

**Comment by debsmith-ux** [comment]
When teams shift to be product-oriented, there isn’t this hand-off. When something breaks, the team that built it has to fix it.

**Comment by debsmith-ux** [comment]
Cross-functional teams must adopt key practices to integrate testing and quality into the process. These practices can include:
Pairing and peer reviews
Static analysis
Chasing out requirement and design defects with BDD and TDD
Creating a solid scaffolding of tests to support the test pyramid tied into the continuous integration system

**Comment by debsmith-ux** [comment]
Gartner Solution Path for Testing Software Applilcations
![](https://www.gartner.com/resources/351000/351011/351011_0004.png)

**Comment by debsmith-ux** [comment]
Recommendations:
Utilize continuous integration and CD as a foundation to drive a continuous approach to quality.
Drive testing focus based on the test pyramid and shift to test automation — note that exploratory testing as well as usability will continue to be manual.

**Comment by debsmith-ux** [comment]
![](https://www.gartner.com/resources/351000/351011/351011_0005.png)

**Comment by debsmith-ux** [comment]
Recommendations:
Drive faster feedback loops and early error detection via shift-left activities.
Recognize the importance of user feedback and deliver value by utilizing shift-right measurement and monitoring.

**Comment by debsmith-ux** [comment]
As Microsoft discovered, you cannot be a master of that which you do not do.

**Comment by debsmith-ux** [comment]
![](https://www.gartner.com/resources/351000/351011/351011_0006.png)

**Comment by debsmith-ux** [comment]
![](https://www.gartner.com/resources/351000/351011/351011_0007.png)

**Comment by debsmith-ux** [comment]
![](https://www.gartner.com/resources/351000/351011/351011_0008.png)

**Comment by debsmith-ux** [comment]
![](https://www.gartner.com/resources/351000/351011/351011_0009.png)

**Comment by debsmith-ux** [comment]
https://www.macmillanhighered.com/brainhoney/resource/6698/digital_first_content/trunk/test/techcomm11e_full/techcomm11e_full_ch13_5.html

**Comment by debsmith-ux** [comment]
THE BASIC PRINCIPLES OF USABILITY TESTING
Three basic principles underlie usability testing:

Usability testing permeates product development. Usability testing involves testing the document, site, or software rigorously and often to make sure it works and is easy to use. Prototypes, newly completed products, and products that have been in use for a while are all tested.
Usability testing involves studying real users as they use the product. Unlike usability evaluations, which often involve experts, testing is done by real users, who can provide important information that experts cannot. Real users make mistakes that experts don’t make. One well-known example relates to computer software that included an error-recovery message that said, “Press Any Key to Continue.” The manufacturer received hundreds of calls from users who couldn’t find the “Any” key.
Usability testing involves setting measurable goals and determining whether the product meets them. Usability testing involves determining, first, what the user is supposed to be able to do. For instance, in testing a wiki, the testers might decide that the user should be able to find the “Edit” function and then edit and save a sentence successfully in less than 30 seconds.
