### ISSUE TITLE
List tools on toolkit

### ISSUE THREAD

**Issue by CraigBuckmaster** [paladinarcher/accelerators#18]
**Description**
Assemble a list of tools from Design Thinking Toolkit book and other sources that are easily accessible to the team.

**Acceptance Criteria**
- [x] Ensure that all mural templates made available have a link for easy access by team members

- [x] Create epic for all non-available tools we wish to make accessible
- [x] Add to P&A or DL blog and link to it.

**Comment by eapowell** [comment]
Blog Posts on Developer Level
https://developerlevel.com/2021/01/22/1085/
Design Thinking Toolbox
http://developerlevel.com/2021/01/22/the-design-toolbox/
