### ISSUE TITLE
API/Swagger Template & Readme Template

### ISSUE THREAD

**Issue by CraigBuckmaster** [paladinarcher/accelerators#20]
**Description:**
API/Swagger Template & Readme Template
I want a template for creating a new API/Swagger file so I
can easily create a new API in a swagger.yaml file. 
& also
I want a Readme template so that I can easily 
and quickly setup a Readme for the new API

**Acceptance Criteria**
API/Swagger Template

- [x] Use .yaml format

- [x] Follow OpenAPI Specifications

- [x] Provide 'fill in the blank' values for a general API design

API Readme Template
 - [x] Use technical language to define the functionalities of the API
 
 - [x] Is specific to an API as opposed to just a general project
 
 - [x] Create instructions for use that are easy to follow

**Comment by thegoodman99** [comment]
Repo found [here](https://github.com/paladinarcher/api-readme-template).
