### ISSUE TITLE
Find better ways to expedite user testing

### ISSUE THREAD

**Issue by CraigBuckmaster** [paladinarcher/accelerators#64]
**Enabler Feature Description:** 
The setup process for user testing needs to be thought out and planned to make it easier/quicker to accomplish. 

**Benefit Hypothesis:** 
“We expect quicker user testing will help enable the tasks in order to achieve the business outcome”.

**Acceptance Criteria:**
- [x] Brainstorm with Mural 

[Enabler Feature Template & Guide](https://paladinarcher-my.sharepoint.com/:w:/r/personal/debra_paladinarcher_com/_layouts/15/Doc.aspx?sourcedoc=%7B7c1311e8-52b0-4111-8c79-4b7d3ae2c282%7D&action=editnew&wdPreviousSession=d9c393c4-b04a-4aca-8ef5-2e85c5278d89&wdNewAndOpenCt=1607042699518&wdo=4&wdOrigin=wacFileNew&wdTpl=blank&wdLcid=1033&wdPreviousCorrelation=f0dcef30-e21c-401a-b960-dcbd987e85ac)

**Comment by eapowell** [comment]
test comment
