### ISSUE TITLE
Craig Customer Facing Success Case Study

### ISSUE THREAD

**Issue by debsmith-ux** [paladinarcher/accelerators#73]
**Enabler Feature Description:**
Success cases, where we improved our clients' lives.
A case study of when we made a difference.

**Benefit Hypothesis:**
We expect the studies to provide many benefits: the creation of customer database, success metrics, material for proposals, generating ideas for others on how they might contribute, and recognizing success.

**Acceptance Criteria:**

- [x] Used Case Study 1 page template

- [x] A success story

- [x] Aligns with our company's purpose

- [x] Has been added to the repo

**Nonfunctional Requirements (NFRs):**

- [x] Use the case study template in Microsoft word

- [x]   Store in Sharepoint

**Comment by CraigBuckmaster** [comment]
https://paladinarcher.sharepoint.com/:w:/g/ESkaiFrz34BLnYE8jKcbmtUBgIHvAew7uSGJvznOzEbaCw?e=5gzSvm
