### ISSUE TITLE
Paul Customer Facing Success Case Study

### ISSUE THREAD

**Issue by debsmith-ux** [paladinarcher/accelerators#74]
**Enabler Feature Description:**
Success cases, where we improved our clients' lives.
A case study of when we made a difference.

**Benefit Hypothesis:**
We expect the studies to provide many benefits: the creation of customer database, success metrics, material for proposals, generating ideas for others on how they might contribute, and recognizing success.

**Acceptance Criteria:**

- [x] Used Case Study 1 page template

- [x] A success story

- [x] Aligns with our company's purpose

- [x] Has been added to the repo

**Nonfunctional Requirements (NFRs):**

- [x] Use the case study template in Microsoft word

- [x]  Store in Sharepoint
https://paladinarcher.sharepoint.com/:w:/r/_layouts/15/Doc.aspx?sourcedoc=%7B193EBE9B-0405-4111-94CA-D8876F620E4A%7D&file=P%26A-Service-Case-Study-Paul-1.docx&action=default&mobileredirect=true

**Comment by CraigBuckmaster** [comment]
Can we add some screenshots to this maybe? If you still have access to JIRA.
