### ISSUE TITLE
Darren Customer Facing Success Case Study

### ISSUE THREAD

**Issue by debsmith-ux** [paladinarcher/accelerators#78]
**Enabler Feature Description:**
Success cases, where we improved our clients' lives.
A case study of when we made a difference.

**Benefit Hypothesis:**
We expect the studies to provide many benefits: the creation of customer database, success metrics, material for proposals, generating ideas for others on how they might contribute, and recognizing success.

**Acceptance Criteria:**

[] Used Case Study 1 page template

[] A success story

[]Aligns with our company's purpose

[] Has been added to the repo

**Nonfunctional Requirements (NFRs):**

[] Use the case study template in Microsoft word

[]  Store in Sharepoint

**Comment by DarrenMoody** [comment]
[P&A-Case-Study-DAS-Mock-Switch-12-10-2020.docx](https://github.com/paladinarcher/accelerators/files/5676495/P.A-Case-Study-DAS-Mock-Switch-12-10-2020.docx)
Link to my case study:
https://paladinarcher.sharepoint.com/:w:/r/_layouts/15/Doc.aspx?sourcedoc=%7BA9EED588-CC99-4FA2-994A-7EC501EF5703%7D&file=P%26A-Case-Study-DAS-Mock-Switch-12-10-2020.docx&action=default&mobileredirect=true
